name: Run Selenium Script

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI
  schedule:
    - cron: '0 9 * * *' # Runs at 9:00 AM daily (optional, customize as needed)

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      # Step 4: Download and set up Chrome
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable' # Install the latest stable version of Chrome

      # Step 5: Run the script
      - name: Run Selenium script
        run: python main.py
